
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer />

        <div className="min-h-screen flex flex-col bg-zinc-50 font-sans dark:bg-black">
          
          <Header />

          {/* 👇 ده أهم تعديل */}
          <main className="flex-1 flex flex-col">
            {children}
          </main>

          <Footer />

        </div>
      </body>
    </html>
  );
}
